---
services:
  databases:
      image: mysql:5.5
      container_name: mysql-db
      environment:
          MYSQL_ROOT_PASSWORD: abcd@1234
      ports:
        - "3306:3306"
  webserver:
      image: 4573173/webserver_php:v1
      container_name: apache
      ports:
        - "80:80"
      depends_on:
        - databases
      volumes:
        - ./apache:/var/www/html
        - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      ports:
        - "8081:80"
      depends_on:
        - databases
      environment:
          PMA_HOST: 'databases'
...

